apiVersion: apps.cozystack.io/v1alpha1
kind: Tenant
metadata:
  name: kuberoot
  namespace: tenant-root
spec:
  etcd: false
  ingress: false
  monitoring: false
  seaweedfs: false
  resourceQuotas:
    cpu: "120"
    memory: 140Gi
