//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The kuberoot Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	node "github.com/tym83/kuberoot/pkg/apis/node"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*BootEntry)(nil), (*node.BootEntry)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BootEntry_To_node_BootEntry(a.(*BootEntry), b.(*node.BootEntry), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.BootEntry)(nil), (*BootEntry)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_BootEntry_To_v1alpha1_BootEntry(a.(*node.BootEntry), b.(*BootEntry), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BootEntryList)(nil), (*node.BootEntryList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BootEntryList_To_node_BootEntryList(a.(*BootEntryList), b.(*node.BootEntryList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.BootEntryList)(nil), (*BootEntryList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_BootEntryList_To_v1alpha1_BootEntryList(a.(*node.BootEntryList), b.(*BootEntryList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BootEntrySpec)(nil), (*node.BootEntrySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BootEntrySpec_To_node_BootEntrySpec(a.(*BootEntrySpec), b.(*node.BootEntrySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.BootEntrySpec)(nil), (*BootEntrySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_BootEntrySpec_To_v1alpha1_BootEntrySpec(a.(*node.BootEntrySpec), b.(*BootEntrySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*BootEntryStatus)(nil), (*node.BootEntryStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_BootEntryStatus_To_node_BootEntryStatus(a.(*BootEntryStatus), b.(*node.BootEntryStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.BootEntryStatus)(nil), (*BootEntryStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_BootEntryStatus_To_v1alpha1_BootEntryStatus(a.(*node.BootEntryStatus), b.(*BootEntryStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Disk)(nil), (*node.Disk)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Disk_To_node_Disk(a.(*Disk), b.(*node.Disk), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.Disk)(nil), (*Disk)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_Disk_To_v1alpha1_Disk(a.(*node.Disk), b.(*Disk), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DiskList)(nil), (*node.DiskList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DiskList_To_node_DiskList(a.(*DiskList), b.(*node.DiskList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.DiskList)(nil), (*DiskList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_DiskList_To_v1alpha1_DiskList(a.(*node.DiskList), b.(*DiskList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DiskPartition)(nil), (*node.DiskPartition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DiskPartition_To_node_DiskPartition(a.(*DiskPartition), b.(*node.DiskPartition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.DiskPartition)(nil), (*DiskPartition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_DiskPartition_To_v1alpha1_DiskPartition(a.(*node.DiskPartition), b.(*DiskPartition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DiskStatus)(nil), (*node.DiskStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_DiskStatus_To_node_DiskStatus(a.(*DiskStatus), b.(*node.DiskStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.DiskStatus)(nil), (*DiskStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_DiskStatus_To_v1alpha1_DiskStatus(a.(*node.DiskStatus), b.(*DiskStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Installation)(nil), (*node.Installation)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Installation_To_node_Installation(a.(*Installation), b.(*node.Installation), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.Installation)(nil), (*Installation)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_Installation_To_v1alpha1_Installation(a.(*node.Installation), b.(*Installation), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InstallationList)(nil), (*node.InstallationList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InstallationList_To_node_InstallationList(a.(*InstallationList), b.(*node.InstallationList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.InstallationList)(nil), (*InstallationList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_InstallationList_To_v1alpha1_InstallationList(a.(*node.InstallationList), b.(*InstallationList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InstallationRestore)(nil), (*node.InstallationRestore)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InstallationRestore_To_node_InstallationRestore(a.(*InstallationRestore), b.(*node.InstallationRestore), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.InstallationRestore)(nil), (*InstallationRestore)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_InstallationRestore_To_v1alpha1_InstallationRestore(a.(*node.InstallationRestore), b.(*InstallationRestore), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InstallationSpec)(nil), (*node.InstallationSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InstallationSpec_To_node_InstallationSpec(a.(*InstallationSpec), b.(*node.InstallationSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.InstallationSpec)(nil), (*InstallationSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_InstallationSpec_To_v1alpha1_InstallationSpec(a.(*node.InstallationSpec), b.(*InstallationSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InstallationStatus)(nil), (*node.InstallationStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InstallationStatus_To_node_InstallationStatus(a.(*InstallationStatus), b.(*node.InstallationStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.InstallationStatus)(nil), (*InstallationStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_InstallationStatus_To_v1alpha1_InstallationStatus(a.(*node.InstallationStatus), b.(*InstallationStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*JoinTicket)(nil), (*node.JoinTicket)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_JoinTicket_To_node_JoinTicket(a.(*JoinTicket), b.(*node.JoinTicket), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.JoinTicket)(nil), (*JoinTicket)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_JoinTicket_To_v1alpha1_JoinTicket(a.(*node.JoinTicket), b.(*JoinTicket), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*JoinTicketList)(nil), (*node.JoinTicketList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_JoinTicketList_To_node_JoinTicketList(a.(*JoinTicketList), b.(*node.JoinTicketList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.JoinTicketList)(nil), (*JoinTicketList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_JoinTicketList_To_v1alpha1_JoinTicketList(a.(*node.JoinTicketList), b.(*JoinTicketList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*JoinTicketSpec)(nil), (*node.JoinTicketSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_JoinTicketSpec_To_node_JoinTicketSpec(a.(*JoinTicketSpec), b.(*node.JoinTicketSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.JoinTicketSpec)(nil), (*JoinTicketSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_JoinTicketSpec_To_v1alpha1_JoinTicketSpec(a.(*node.JoinTicketSpec), b.(*JoinTicketSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*JoinTicketStatus)(nil), (*node.JoinTicketStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_JoinTicketStatus_To_node_JoinTicketStatus(a.(*JoinTicketStatus), b.(*node.JoinTicketStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.JoinTicketStatus)(nil), (*JoinTicketStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_JoinTicketStatus_To_v1alpha1_JoinTicketStatus(a.(*node.JoinTicketStatus), b.(*JoinTicketStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Kubeconfig)(nil), (*node.Kubeconfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Kubeconfig_To_node_Kubeconfig(a.(*Kubeconfig), b.(*node.Kubeconfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.Kubeconfig)(nil), (*Kubeconfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_Kubeconfig_To_v1alpha1_Kubeconfig(a.(*node.Kubeconfig), b.(*Kubeconfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*KubeconfigList)(nil), (*node.KubeconfigList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_KubeconfigList_To_node_KubeconfigList(a.(*KubeconfigList), b.(*node.KubeconfigList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.KubeconfigList)(nil), (*KubeconfigList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_KubeconfigList_To_v1alpha1_KubeconfigList(a.(*node.KubeconfigList), b.(*KubeconfigList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Membership)(nil), (*node.Membership)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Membership_To_node_Membership(a.(*Membership), b.(*node.Membership), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.Membership)(nil), (*Membership)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_Membership_To_v1alpha1_Membership(a.(*node.Membership), b.(*Membership), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MembershipList)(nil), (*node.MembershipList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MembershipList_To_node_MembershipList(a.(*MembershipList), b.(*node.MembershipList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.MembershipList)(nil), (*MembershipList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_MembershipList_To_v1alpha1_MembershipList(a.(*node.MembershipList), b.(*MembershipList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MembershipSpec)(nil), (*node.MembershipSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MembershipSpec_To_node_MembershipSpec(a.(*MembershipSpec), b.(*node.MembershipSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.MembershipSpec)(nil), (*MembershipSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_MembershipSpec_To_v1alpha1_MembershipSpec(a.(*node.MembershipSpec), b.(*MembershipSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MembershipStatus)(nil), (*node.MembershipStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MembershipStatus_To_node_MembershipStatus(a.(*MembershipStatus), b.(*node.MembershipStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.MembershipStatus)(nil), (*MembershipStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_MembershipStatus_To_v1alpha1_MembershipStatus(a.(*node.MembershipStatus), b.(*MembershipStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NodeService)(nil), (*node.NodeService)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NodeService_To_node_NodeService(a.(*NodeService), b.(*node.NodeService), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.NodeService)(nil), (*NodeService)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_NodeService_To_v1alpha1_NodeService(a.(*node.NodeService), b.(*NodeService), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NodeServiceList)(nil), (*node.NodeServiceList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NodeServiceList_To_node_NodeServiceList(a.(*NodeServiceList), b.(*node.NodeServiceList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.NodeServiceList)(nil), (*NodeServiceList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_NodeServiceList_To_v1alpha1_NodeServiceList(a.(*node.NodeServiceList), b.(*NodeServiceList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NodeServiceSpec)(nil), (*node.NodeServiceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NodeServiceSpec_To_node_NodeServiceSpec(a.(*NodeServiceSpec), b.(*node.NodeServiceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.NodeServiceSpec)(nil), (*NodeServiceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_NodeServiceSpec_To_v1alpha1_NodeServiceSpec(a.(*node.NodeServiceSpec), b.(*NodeServiceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NodeServiceStatus)(nil), (*node.NodeServiceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NodeServiceStatus_To_node_NodeServiceStatus(a.(*NodeServiceStatus), b.(*node.NodeServiceStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.NodeServiceStatus)(nil), (*NodeServiceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_NodeServiceStatus_To_v1alpha1_NodeServiceStatus(a.(*node.NodeServiceStatus), b.(*NodeServiceStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OSConfig)(nil), (*node.OSConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_OSConfig_To_node_OSConfig(a.(*OSConfig), b.(*node.OSConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.OSConfig)(nil), (*OSConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_OSConfig_To_v1alpha1_OSConfig(a.(*node.OSConfig), b.(*OSConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OSConfigList)(nil), (*node.OSConfigList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_OSConfigList_To_node_OSConfigList(a.(*OSConfigList), b.(*node.OSConfigList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.OSConfigList)(nil), (*OSConfigList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_OSConfigList_To_v1alpha1_OSConfigList(a.(*node.OSConfigList), b.(*OSConfigList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OSConfigSpec)(nil), (*node.OSConfigSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_OSConfigSpec_To_node_OSConfigSpec(a.(*OSConfigSpec), b.(*node.OSConfigSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.OSConfigSpec)(nil), (*OSConfigSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_OSConfigSpec_To_v1alpha1_OSConfigSpec(a.(*node.OSConfigSpec), b.(*OSConfigSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*OSConfigStatus)(nil), (*node.OSConfigStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_OSConfigStatus_To_node_OSConfigStatus(a.(*OSConfigStatus), b.(*node.OSConfigStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.OSConfigStatus)(nil), (*OSConfigStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_OSConfigStatus_To_v1alpha1_OSConfigStatus(a.(*node.OSConfigStatus), b.(*OSConfigStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*StateBackup)(nil), (*node.StateBackup)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_StateBackup_To_node_StateBackup(a.(*StateBackup), b.(*node.StateBackup), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.StateBackup)(nil), (*StateBackup)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_StateBackup_To_v1alpha1_StateBackup(a.(*node.StateBackup), b.(*StateBackup), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*StateBackupList)(nil), (*node.StateBackupList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_StateBackupList_To_node_StateBackupList(a.(*StateBackupList), b.(*node.StateBackupList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.StateBackupList)(nil), (*StateBackupList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_StateBackupList_To_v1alpha1_StateBackupList(a.(*node.StateBackupList), b.(*StateBackupList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*StateBackupStatus)(nil), (*node.StateBackupStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_StateBackupStatus_To_node_StateBackupStatus(a.(*StateBackupStatus), b.(*node.StateBackupStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.StateBackupStatus)(nil), (*StateBackupStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_StateBackupStatus_To_v1alpha1_StateBackupStatus(a.(*node.StateBackupStatus), b.(*StateBackupStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Upgrade)(nil), (*node.Upgrade)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Upgrade_To_node_Upgrade(a.(*Upgrade), b.(*node.Upgrade), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.Upgrade)(nil), (*Upgrade)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_Upgrade_To_v1alpha1_Upgrade(a.(*node.Upgrade), b.(*Upgrade), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*UpgradeList)(nil), (*node.UpgradeList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_UpgradeList_To_node_UpgradeList(a.(*UpgradeList), b.(*node.UpgradeList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.UpgradeList)(nil), (*UpgradeList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_UpgradeList_To_v1alpha1_UpgradeList(a.(*node.UpgradeList), b.(*UpgradeList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*UpgradeSpec)(nil), (*node.UpgradeSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_UpgradeSpec_To_node_UpgradeSpec(a.(*UpgradeSpec), b.(*node.UpgradeSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.UpgradeSpec)(nil), (*UpgradeSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_UpgradeSpec_To_v1alpha1_UpgradeSpec(a.(*node.UpgradeSpec), b.(*UpgradeSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*UpgradeStatus)(nil), (*node.UpgradeStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_UpgradeStatus_To_node_UpgradeStatus(a.(*UpgradeStatus), b.(*node.UpgradeStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*node.UpgradeStatus)(nil), (*UpgradeStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_node_UpgradeStatus_To_v1alpha1_UpgradeStatus(a.(*node.UpgradeStatus), b.(*UpgradeStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_BootEntry_To_node_BootEntry(in *BootEntry, out *node.BootEntry, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_BootEntrySpec_To_node_BootEntrySpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_BootEntryStatus_To_node_BootEntryStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_BootEntry_To_node_BootEntry is an autogenerated conversion function.
func Convert_v1alpha1_BootEntry_To_node_BootEntry(in *BootEntry, out *node.BootEntry, s conversion.Scope) error {
	return autoConvert_v1alpha1_BootEntry_To_node_BootEntry(in, out, s)
}

func autoConvert_node_BootEntry_To_v1alpha1_BootEntry(in *node.BootEntry, out *BootEntry, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_node_BootEntrySpec_To_v1alpha1_BootEntrySpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_node_BootEntryStatus_To_v1alpha1_BootEntryStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_node_BootEntry_To_v1alpha1_BootEntry is an autogenerated conversion function.
func Convert_node_BootEntry_To_v1alpha1_BootEntry(in *node.BootEntry, out *BootEntry, s conversion.Scope) error {
	return autoConvert_node_BootEntry_To_v1alpha1_BootEntry(in, out, s)
}

func autoConvert_v1alpha1_BootEntryList_To_node_BootEntryList(in *BootEntryList, out *node.BootEntryList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]node.BootEntry)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_BootEntryList_To_node_BootEntryList is an autogenerated conversion function.
func Convert_v1alpha1_BootEntryList_To_node_BootEntryList(in *BootEntryList, out *node.BootEntryList, s conversion.Scope) error {
	return autoConvert_v1alpha1_BootEntryList_To_node_BootEntryList(in, out, s)
}

func autoConvert_node_BootEntryList_To_v1alpha1_BootEntryList(in *node.BootEntryList, out *BootEntryList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]BootEntry)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_node_BootEntryList_To_v1alpha1_BootEntryList is an autogenerated conversion function.
func Convert_node_BootEntryList_To_v1alpha1_BootEntryList(in *node.BootEntryList, out *BootEntryList, s conversion.Scope) error {
	return autoConvert_node_BootEntryList_To_v1alpha1_BootEntryList(in, out, s)
}

func autoConvert_v1alpha1_BootEntrySpec_To_node_BootEntrySpec(in *BootEntrySpec, out *node.BootEntrySpec, s conversion.Scope) error {
	*out = *(*node.BootEntrySpec)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_BootEntrySpec_To_node_BootEntrySpec is an autogenerated conversion function.
func Convert_v1alpha1_BootEntrySpec_To_node_BootEntrySpec(in *BootEntrySpec, out *node.BootEntrySpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_BootEntrySpec_To_node_BootEntrySpec(in, out, s)
}

func autoConvert_node_BootEntrySpec_To_v1alpha1_BootEntrySpec(in *node.BootEntrySpec, out *BootEntrySpec, s conversion.Scope) error {
	*out = *(*BootEntrySpec)(unsafe.Pointer(in))
	return nil
}

// Convert_node_BootEntrySpec_To_v1alpha1_BootEntrySpec is an autogenerated conversion function.
func Convert_node_BootEntrySpec_To_v1alpha1_BootEntrySpec(in *node.BootEntrySpec, out *BootEntrySpec, s conversion.Scope) error {
	return autoConvert_node_BootEntrySpec_To_v1alpha1_BootEntrySpec(in, out, s)
}

func autoConvert_v1alpha1_BootEntryStatus_To_node_BootEntryStatus(in *BootEntryStatus, out *node.BootEntryStatus, s conversion.Scope) error {
	*out = *(*node.BootEntryStatus)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_BootEntryStatus_To_node_BootEntryStatus is an autogenerated conversion function.
func Convert_v1alpha1_BootEntryStatus_To_node_BootEntryStatus(in *BootEntryStatus, out *node.BootEntryStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_BootEntryStatus_To_node_BootEntryStatus(in, out, s)
}

func autoConvert_node_BootEntryStatus_To_v1alpha1_BootEntryStatus(in *node.BootEntryStatus, out *BootEntryStatus, s conversion.Scope) error {
	*out = *(*BootEntryStatus)(unsafe.Pointer(in))
	return nil
}

// Convert_node_BootEntryStatus_To_v1alpha1_BootEntryStatus is an autogenerated conversion function.
func Convert_node_BootEntryStatus_To_v1alpha1_BootEntryStatus(in *node.BootEntryStatus, out *BootEntryStatus, s conversion.Scope) error {
	return autoConvert_node_BootEntryStatus_To_v1alpha1_BootEntryStatus(in, out, s)
}

func autoConvert_v1alpha1_Disk_To_node_Disk(in *Disk, out *node.Disk, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_DiskStatus_To_node_DiskStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Disk_To_node_Disk is an autogenerated conversion function.
func Convert_v1alpha1_Disk_To_node_Disk(in *Disk, out *node.Disk, s conversion.Scope) error {
	return autoConvert_v1alpha1_Disk_To_node_Disk(in, out, s)
}

func autoConvert_node_Disk_To_v1alpha1_Disk(in *node.Disk, out *Disk, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_node_DiskStatus_To_v1alpha1_DiskStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_node_Disk_To_v1alpha1_Disk is an autogenerated conversion function.
func Convert_node_Disk_To_v1alpha1_Disk(in *node.Disk, out *Disk, s conversion.Scope) error {
	return autoConvert_node_Disk_To_v1alpha1_Disk(in, out, s)
}

func autoConvert_v1alpha1_DiskList_To_node_DiskList(in *DiskList, out *node.DiskList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]node.Disk)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_DiskList_To_node_DiskList is an autogenerated conversion function.
func Convert_v1alpha1_DiskList_To_node_DiskList(in *DiskList, out *node.DiskList, s conversion.Scope) error {
	return autoConvert_v1alpha1_DiskList_To_node_DiskList(in, out, s)
}

func autoConvert_node_DiskList_To_v1alpha1_DiskList(in *node.DiskList, out *DiskList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Disk)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_node_DiskList_To_v1alpha1_DiskList is an autogenerated conversion function.
func Convert_node_DiskList_To_v1alpha1_DiskList(in *node.DiskList, out *DiskList, s conversion.Scope) error {
	return autoConvert_node_DiskList_To_v1alpha1_DiskList(in, out, s)
}

func autoConvert_v1alpha1_DiskPartition_To_node_DiskPartition(in *DiskPartition, out *node.DiskPartition, s conversion.Scope) error {
	*out = *(*node.DiskPartition)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_DiskPartition_To_node_DiskPartition is an autogenerated conversion function.
func Convert_v1alpha1_DiskPartition_To_node_DiskPartition(in *DiskPartition, out *node.DiskPartition, s conversion.Scope) error {
	return autoConvert_v1alpha1_DiskPartition_To_node_DiskPartition(in, out, s)
}

func autoConvert_node_DiskPartition_To_v1alpha1_DiskPartition(in *node.DiskPartition, out *DiskPartition, s conversion.Scope) error {
	*out = *(*DiskPartition)(unsafe.Pointer(in))
	return nil
}

// Convert_node_DiskPartition_To_v1alpha1_DiskPartition is an autogenerated conversion function.
func Convert_node_DiskPartition_To_v1alpha1_DiskPartition(in *node.DiskPartition, out *DiskPartition, s conversion.Scope) error {
	return autoConvert_node_DiskPartition_To_v1alpha1_DiskPartition(in, out, s)
}

func autoConvert_v1alpha1_DiskStatus_To_node_DiskStatus(in *DiskStatus, out *node.DiskStatus, s conversion.Scope) error {
	*out = *(*node.DiskStatus)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_DiskStatus_To_node_DiskStatus is an autogenerated conversion function.
func Convert_v1alpha1_DiskStatus_To_node_DiskStatus(in *DiskStatus, out *node.DiskStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_DiskStatus_To_node_DiskStatus(in, out, s)
}

func autoConvert_node_DiskStatus_To_v1alpha1_DiskStatus(in *node.DiskStatus, out *DiskStatus, s conversion.Scope) error {
	*out = *(*DiskStatus)(unsafe.Pointer(in))
	return nil
}

// Convert_node_DiskStatus_To_v1alpha1_DiskStatus is an autogenerated conversion function.
func Convert_node_DiskStatus_To_v1alpha1_DiskStatus(in *node.DiskStatus, out *DiskStatus, s conversion.Scope) error {
	return autoConvert_node_DiskStatus_To_v1alpha1_DiskStatus(in, out, s)
}

func autoConvert_v1alpha1_Installation_To_node_Installation(in *Installation, out *node.Installation, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_InstallationSpec_To_node_InstallationSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_InstallationStatus_To_node_InstallationStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Installation_To_node_Installation is an autogenerated conversion function.
func Convert_v1alpha1_Installation_To_node_Installation(in *Installation, out *node.Installation, s conversion.Scope) error {
	return autoConvert_v1alpha1_Installation_To_node_Installation(in, out, s)
}

func autoConvert_node_Installation_To_v1alpha1_Installation(in *node.Installation, out *Installation, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_node_InstallationSpec_To_v1alpha1_InstallationSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_node_InstallationStatus_To_v1alpha1_InstallationStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_node_Installation_To_v1alpha1_Installation is an autogenerated conversion function.
func Convert_node_Installation_To_v1alpha1_Installation(in *node.Installation, out *Installation, s conversion.Scope) error {
	return autoConvert_node_Installation_To_v1alpha1_Installation(in, out, s)
}

func autoConvert_v1alpha1_InstallationList_To_node_InstallationList(in *InstallationList, out *node.InstallationList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]node.Installation)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_InstallationList_To_node_InstallationList is an autogenerated conversion function.
func Convert_v1alpha1_InstallationList_To_node_InstallationList(in *InstallationList, out *node.InstallationList, s conversion.Scope) error {
	return autoConvert_v1alpha1_InstallationList_To_node_InstallationList(in, out, s)
}

func autoConvert_node_InstallationList_To_v1alpha1_InstallationList(in *node.InstallationList, out *InstallationList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Installation)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_node_InstallationList_To_v1alpha1_InstallationList is an autogenerated conversion function.
func Convert_node_InstallationList_To_v1alpha1_InstallationList(in *node.InstallationList, out *InstallationList, s conversion.Scope) error {
	return autoConvert_node_InstallationList_To_v1alpha1_InstallationList(in, out, s)
}

func autoConvert_v1alpha1_InstallationRestore_To_node_InstallationRestore(in *InstallationRestore, out *node.InstallationRestore, s conversion.Scope) error {
	*out = *(*node.InstallationRestore)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_InstallationRestore_To_node_InstallationRestore is an autogenerated conversion function.
func Convert_v1alpha1_InstallationRestore_To_node_InstallationRestore(in *InstallationRestore, out *node.InstallationRestore, s conversion.Scope) error {
	return autoConvert_v1alpha1_InstallationRestore_To_node_InstallationRestore(in, out, s)
}

func autoConvert_node_InstallationRestore_To_v1alpha1_InstallationRestore(in *node.InstallationRestore, out *InstallationRestore, s conversion.Scope) error {
	*out = *(*InstallationRestore)(unsafe.Pointer(in))
	return nil
}

// Convert_node_InstallationRestore_To_v1alpha1_InstallationRestore is an autogenerated conversion function.
func Convert_node_InstallationRestore_To_v1alpha1_InstallationRestore(in *node.InstallationRestore, out *InstallationRestore, s conversion.Scope) error {
	return autoConvert_node_InstallationRestore_To_v1alpha1_InstallationRestore(in, out, s)
}

func autoConvert_v1alpha1_InstallationSpec_To_node_InstallationSpec(in *InstallationSpec, out *node.InstallationSpec, s conversion.Scope) error {
	*out = *(*node.InstallationSpec)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_InstallationSpec_To_node_InstallationSpec is an autogenerated conversion function.
func Convert_v1alpha1_InstallationSpec_To_node_InstallationSpec(in *InstallationSpec, out *node.InstallationSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_InstallationSpec_To_node_InstallationSpec(in, out, s)
}

func autoConvert_node_InstallationSpec_To_v1alpha1_InstallationSpec(in *node.InstallationSpec, out *InstallationSpec, s conversion.Scope) error {
	*out = *(*InstallationSpec)(unsafe.Pointer(in))
	return nil
}

// Convert_node_InstallationSpec_To_v1alpha1_InstallationSpec is an autogenerated conversion function.
func Convert_node_InstallationSpec_To_v1alpha1_InstallationSpec(in *node.InstallationSpec, out *InstallationSpec, s conversion.Scope) error {
	return autoConvert_node_InstallationSpec_To_v1alpha1_InstallationSpec(in, out, s)
}

func autoConvert_v1alpha1_InstallationStatus_To_node_InstallationStatus(in *InstallationStatus, out *node.InstallationStatus, s conversion.Scope) error {
	*out = *(*node.InstallationStatus)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_InstallationStatus_To_node_InstallationStatus is an autogenerated conversion function.
func Convert_v1alpha1_InstallationStatus_To_node_InstallationStatus(in *InstallationStatus, out *node.InstallationStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_InstallationStatus_To_node_InstallationStatus(in, out, s)
}

func autoConvert_node_InstallationStatus_To_v1alpha1_InstallationStatus(in *node.InstallationStatus, out *InstallationStatus, s conversion.Scope) error {
	*out = *(*InstallationStatus)(unsafe.Pointer(in))
	return nil
}

// Convert_node_InstallationStatus_To_v1alpha1_InstallationStatus is an autogenerated conversion function.
func Convert_node_InstallationStatus_To_v1alpha1_InstallationStatus(in *node.InstallationStatus, out *InstallationStatus, s conversion.Scope) error {
	return autoConvert_node_InstallationStatus_To_v1alpha1_InstallationStatus(in, out, s)
}

func autoConvert_v1alpha1_JoinTicket_To_node_JoinTicket(in *JoinTicket, out *node.JoinTicket, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_JoinTicketSpec_To_node_JoinTicketSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_JoinTicketStatus_To_node_JoinTicketStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_JoinTicket_To_node_JoinTicket is an autogenerated conversion function.
func Convert_v1alpha1_JoinTicket_To_node_JoinTicket(in *JoinTicket, out *node.JoinTicket, s conversion.Scope) error {
	return autoConvert_v1alpha1_JoinTicket_To_node_JoinTicket(in, out, s)
}

func autoConvert_node_JoinTicket_To_v1alpha1_JoinTicket(in *node.JoinTicket, out *JoinTicket, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_node_JoinTicketSpec_To_v1alpha1_JoinTicketSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_node_JoinTicketStatus_To_v1alpha1_JoinTicketStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_node_JoinTicket_To_v1alpha1_JoinTicket is an autogenerated conversion function.
func Convert_node_JoinTicket_To_v1alpha1_JoinTicket(in *node.JoinTicket, out *JoinTicket, s conversion.Scope) error {
	return autoConvert_node_JoinTicket_To_v1alpha1_JoinTicket(in, out, s)
}

func autoConvert_v1alpha1_JoinTicketList_To_node_JoinTicketList(in *JoinTicketList, out *node.JoinTicketList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]node.JoinTicket)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_JoinTicketList_To_node_JoinTicketList is an autogenerated conversion function.
func Convert_v1alpha1_JoinTicketList_To_node_JoinTicketList(in *JoinTicketList, out *node.JoinTicketList, s conversion.Scope) error {
	return autoConvert_v1alpha1_JoinTicketList_To_node_JoinTicketList(in, out, s)
}

func autoConvert_node_JoinTicketList_To_v1alpha1_JoinTicketList(in *node.JoinTicketList, out *JoinTicketList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]JoinTicket)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_node_JoinTicketList_To_v1alpha1_JoinTicketList is an autogenerated conversion function.
func Convert_node_JoinTicketList_To_v1alpha1_JoinTicketList(in *node.JoinTicketList, out *JoinTicketList, s conversion.Scope) error {
	return autoConvert_node_JoinTicketList_To_v1alpha1_JoinTicketList(in, out, s)
}

func autoConvert_v1alpha1_JoinTicketSpec_To_node_JoinTicketSpec(in *JoinTicketSpec, out *node.JoinTicketSpec, s conversion.Scope) error {
	*out = *(*node.JoinTicketSpec)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_JoinTicketSpec_To_node_JoinTicketSpec is an autogenerated conversion function.
func Convert_v1alpha1_JoinTicketSpec_To_node_JoinTicketSpec(in *JoinTicketSpec, out *node.JoinTicketSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_JoinTicketSpec_To_node_JoinTicketSpec(in, out, s)
}

func autoConvert_node_JoinTicketSpec_To_v1alpha1_JoinTicketSpec(in *node.JoinTicketSpec, out *JoinTicketSpec, s conversion.Scope) error {
	*out = *(*JoinTicketSpec)(unsafe.Pointer(in))
	return nil
}

// Convert_node_JoinTicketSpec_To_v1alpha1_JoinTicketSpec is an autogenerated conversion function.
func Convert_node_JoinTicketSpec_To_v1alpha1_JoinTicketSpec(in *node.JoinTicketSpec, out *JoinTicketSpec, s conversion.Scope) error {
	return autoConvert_node_JoinTicketSpec_To_v1alpha1_JoinTicketSpec(in, out, s)
}

func autoConvert_v1alpha1_JoinTicketStatus_To_node_JoinTicketStatus(in *JoinTicketStatus, out *node.JoinTicketStatus, s conversion.Scope) error {
	*out = *(*node.JoinTicketStatus)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_JoinTicketStatus_To_node_JoinTicketStatus is an autogenerated conversion function.
func Convert_v1alpha1_JoinTicketStatus_To_node_JoinTicketStatus(in *JoinTicketStatus, out *node.JoinTicketStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_JoinTicketStatus_To_node_JoinTicketStatus(in, out, s)
}

func autoConvert_node_JoinTicketStatus_To_v1alpha1_JoinTicketStatus(in *node.JoinTicketStatus, out *JoinTicketStatus, s conversion.Scope) error {
	*out = *(*JoinTicketStatus)(unsafe.Pointer(in))
	return nil
}

// Convert_node_JoinTicketStatus_To_v1alpha1_JoinTicketStatus is an autogenerated conversion function.
func Convert_node_JoinTicketStatus_To_v1alpha1_JoinTicketStatus(in *node.JoinTicketStatus, out *JoinTicketStatus, s conversion.Scope) error {
	return autoConvert_node_JoinTicketStatus_To_v1alpha1_JoinTicketStatus(in, out, s)
}

func autoConvert_v1alpha1_Kubeconfig_To_node_Kubeconfig(in *Kubeconfig, out *node.Kubeconfig, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Server = in.Server
	out.Kubeconfig = in.Kubeconfig
	return nil
}

// Convert_v1alpha1_Kubeconfig_To_node_Kubeconfig is an autogenerated conversion function.
func Convert_v1alpha1_Kubeconfig_To_node_Kubeconfig(in *Kubeconfig, out *node.Kubeconfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_Kubeconfig_To_node_Kubeconfig(in, out, s)
}

func autoConvert_node_Kubeconfig_To_v1alpha1_Kubeconfig(in *node.Kubeconfig, out *Kubeconfig, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Server = in.Server
	out.Kubeconfig = in.Kubeconfig
	return nil
}

// Convert_node_Kubeconfig_To_v1alpha1_Kubeconfig is an autogenerated conversion function.
func Convert_node_Kubeconfig_To_v1alpha1_Kubeconfig(in *node.Kubeconfig, out *Kubeconfig, s conversion.Scope) error {
	return autoConvert_node_Kubeconfig_To_v1alpha1_Kubeconfig(in, out, s)
}

func autoConvert_v1alpha1_KubeconfigList_To_node_KubeconfigList(in *KubeconfigList, out *node.KubeconfigList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]node.Kubeconfig)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_KubeconfigList_To_node_KubeconfigList is an autogenerated conversion function.
func Convert_v1alpha1_KubeconfigList_To_node_KubeconfigList(in *KubeconfigList, out *node.KubeconfigList, s conversion.Scope) error {
	return autoConvert_v1alpha1_KubeconfigList_To_node_KubeconfigList(in, out, s)
}

func autoConvert_node_KubeconfigList_To_v1alpha1_KubeconfigList(in *node.KubeconfigList, out *KubeconfigList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Kubeconfig)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_node_KubeconfigList_To_v1alpha1_KubeconfigList is an autogenerated conversion function.
func Convert_node_KubeconfigList_To_v1alpha1_KubeconfigList(in *node.KubeconfigList, out *KubeconfigList, s conversion.Scope) error {
	return autoConvert_node_KubeconfigList_To_v1alpha1_KubeconfigList(in, out, s)
}

func autoConvert_v1alpha1_Membership_To_node_Membership(in *Membership, out *node.Membership, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_MembershipSpec_To_node_MembershipSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_MembershipStatus_To_node_MembershipStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Membership_To_node_Membership is an autogenerated conversion function.
func Convert_v1alpha1_Membership_To_node_Membership(in *Membership, out *node.Membership, s conversion.Scope) error {
	return autoConvert_v1alpha1_Membership_To_node_Membership(in, out, s)
}

func autoConvert_node_Membership_To_v1alpha1_Membership(in *node.Membership, out *Membership, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_node_MembershipSpec_To_v1alpha1_MembershipSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_node_MembershipStatus_To_v1alpha1_MembershipStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_node_Membership_To_v1alpha1_Membership is an autogenerated conversion function.
func Convert_node_Membership_To_v1alpha1_Membership(in *node.Membership, out *Membership, s conversion.Scope) error {
	return autoConvert_node_Membership_To_v1alpha1_Membership(in, out, s)
}

func autoConvert_v1alpha1_MembershipList_To_node_MembershipList(in *MembershipList, out *node.MembershipList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]node.Membership)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_MembershipList_To_node_MembershipList is an autogenerated conversion function.
func Convert_v1alpha1_MembershipList_To_node_MembershipList(in *MembershipList, out *node.MembershipList, s conversion.Scope) error {
	return autoConvert_v1alpha1_MembershipList_To_node_MembershipList(in, out, s)
}

func autoConvert_node_MembershipList_To_v1alpha1_MembershipList(in *node.MembershipList, out *MembershipList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Membership)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_node_MembershipList_To_v1alpha1_MembershipList is an autogenerated conversion function.
func Convert_node_MembershipList_To_v1alpha1_MembershipList(in *node.MembershipList, out *MembershipList, s conversion.Scope) error {
	return autoConvert_node_MembershipList_To_v1alpha1_MembershipList(in, out, s)
}

func autoConvert_v1alpha1_MembershipSpec_To_node_MembershipSpec(in *MembershipSpec, out *node.MembershipSpec, s conversion.Scope) error {
	*out = *(*node.MembershipSpec)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_MembershipSpec_To_node_MembershipSpec is an autogenerated conversion function.
func Convert_v1alpha1_MembershipSpec_To_node_MembershipSpec(in *MembershipSpec, out *node.MembershipSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_MembershipSpec_To_node_MembershipSpec(in, out, s)
}

func autoConvert_node_MembershipSpec_To_v1alpha1_MembershipSpec(in *node.MembershipSpec, out *MembershipSpec, s conversion.Scope) error {
	*out = *(*MembershipSpec)(unsafe.Pointer(in))
	return nil
}

// Convert_node_MembershipSpec_To_v1alpha1_MembershipSpec is an autogenerated conversion function.
func Convert_node_MembershipSpec_To_v1alpha1_MembershipSpec(in *node.MembershipSpec, out *MembershipSpec, s conversion.Scope) error {
	return autoConvert_node_MembershipSpec_To_v1alpha1_MembershipSpec(in, out, s)
}

func autoConvert_v1alpha1_MembershipStatus_To_node_MembershipStatus(in *MembershipStatus, out *node.MembershipStatus, s conversion.Scope) error {
	*out = *(*node.MembershipStatus)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_MembershipStatus_To_node_MembershipStatus is an autogenerated conversion function.
func Convert_v1alpha1_MembershipStatus_To_node_MembershipStatus(in *MembershipStatus, out *node.MembershipStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_MembershipStatus_To_node_MembershipStatus(in, out, s)
}

func autoConvert_node_MembershipStatus_To_v1alpha1_MembershipStatus(in *node.MembershipStatus, out *MembershipStatus, s conversion.Scope) error {
	*out = *(*MembershipStatus)(unsafe.Pointer(in))
	return nil
}

// Convert_node_MembershipStatus_To_v1alpha1_MembershipStatus is an autogenerated conversion function.
func Convert_node_MembershipStatus_To_v1alpha1_MembershipStatus(in *node.MembershipStatus, out *MembershipStatus, s conversion.Scope) error {
	return autoConvert_node_MembershipStatus_To_v1alpha1_MembershipStatus(in, out, s)
}

func autoConvert_v1alpha1_NodeService_To_node_NodeService(in *NodeService, out *node.NodeService, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_NodeServiceSpec_To_node_NodeServiceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_NodeServiceStatus_To_node_NodeServiceStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_NodeService_To_node_NodeService is an autogenerated conversion function.
func Convert_v1alpha1_NodeService_To_node_NodeService(in *NodeService, out *node.NodeService, s conversion.Scope) error {
	return autoConvert_v1alpha1_NodeService_To_node_NodeService(in, out, s)
}

func autoConvert_node_NodeService_To_v1alpha1_NodeService(in *node.NodeService, out *NodeService, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_node_NodeServiceSpec_To_v1alpha1_NodeServiceSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_node_NodeServiceStatus_To_v1alpha1_NodeServiceStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_node_NodeService_To_v1alpha1_NodeService is an autogenerated conversion function.
func Convert_node_NodeService_To_v1alpha1_NodeService(in *node.NodeService, out *NodeService, s conversion.Scope) error {
	return autoConvert_node_NodeService_To_v1alpha1_NodeService(in, out, s)
}

func autoConvert_v1alpha1_NodeServiceList_To_node_NodeServiceList(in *NodeServiceList, out *node.NodeServiceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]node.NodeService)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_NodeServiceList_To_node_NodeServiceList is an autogenerated conversion function.
func Convert_v1alpha1_NodeServiceList_To_node_NodeServiceList(in *NodeServiceList, out *node.NodeServiceList, s conversion.Scope) error {
	return autoConvert_v1alpha1_NodeServiceList_To_node_NodeServiceList(in, out, s)
}

func autoConvert_node_NodeServiceList_To_v1alpha1_NodeServiceList(in *node.NodeServiceList, out *NodeServiceList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]NodeService)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_node_NodeServiceList_To_v1alpha1_NodeServiceList is an autogenerated conversion function.
func Convert_node_NodeServiceList_To_v1alpha1_NodeServiceList(in *node.NodeServiceList, out *NodeServiceList, s conversion.Scope) error {
	return autoConvert_node_NodeServiceList_To_v1alpha1_NodeServiceList(in, out, s)
}

func autoConvert_v1alpha1_NodeServiceSpec_To_node_NodeServiceSpec(in *NodeServiceSpec, out *node.NodeServiceSpec, s conversion.Scope) error {
	*out = *(*node.NodeServiceSpec)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_NodeServiceSpec_To_node_NodeServiceSpec is an autogenerated conversion function.
func Convert_v1alpha1_NodeServiceSpec_To_node_NodeServiceSpec(in *NodeServiceSpec, out *node.NodeServiceSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_NodeServiceSpec_To_node_NodeServiceSpec(in, out, s)
}

func autoConvert_node_NodeServiceSpec_To_v1alpha1_NodeServiceSpec(in *node.NodeServiceSpec, out *NodeServiceSpec, s conversion.Scope) error {
	*out = *(*NodeServiceSpec)(unsafe.Pointer(in))
	return nil
}

// Convert_node_NodeServiceSpec_To_v1alpha1_NodeServiceSpec is an autogenerated conversion function.
func Convert_node_NodeServiceSpec_To_v1alpha1_NodeServiceSpec(in *node.NodeServiceSpec, out *NodeServiceSpec, s conversion.Scope) error {
	return autoConvert_node_NodeServiceSpec_To_v1alpha1_NodeServiceSpec(in, out, s)
}

func autoConvert_v1alpha1_NodeServiceStatus_To_node_NodeServiceStatus(in *NodeServiceStatus, out *node.NodeServiceStatus, s conversion.Scope) error {
	*out = *(*node.NodeServiceStatus)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_NodeServiceStatus_To_node_NodeServiceStatus is an autogenerated conversion function.
func Convert_v1alpha1_NodeServiceStatus_To_node_NodeServiceStatus(in *NodeServiceStatus, out *node.NodeServiceStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_NodeServiceStatus_To_node_NodeServiceStatus(in, out, s)
}

func autoConvert_node_NodeServiceStatus_To_v1alpha1_NodeServiceStatus(in *node.NodeServiceStatus, out *NodeServiceStatus, s conversion.Scope) error {
	*out = *(*NodeServiceStatus)(unsafe.Pointer(in))
	return nil
}

// Convert_node_NodeServiceStatus_To_v1alpha1_NodeServiceStatus is an autogenerated conversion function.
func Convert_node_NodeServiceStatus_To_v1alpha1_NodeServiceStatus(in *node.NodeServiceStatus, out *NodeServiceStatus, s conversion.Scope) error {
	return autoConvert_node_NodeServiceStatus_To_v1alpha1_NodeServiceStatus(in, out, s)
}

func autoConvert_v1alpha1_OSConfig_To_node_OSConfig(in *OSConfig, out *node.OSConfig, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_OSConfigSpec_To_node_OSConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_OSConfigStatus_To_node_OSConfigStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_OSConfig_To_node_OSConfig is an autogenerated conversion function.
func Convert_v1alpha1_OSConfig_To_node_OSConfig(in *OSConfig, out *node.OSConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_OSConfig_To_node_OSConfig(in, out, s)
}

func autoConvert_node_OSConfig_To_v1alpha1_OSConfig(in *node.OSConfig, out *OSConfig, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_node_OSConfigSpec_To_v1alpha1_OSConfigSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_node_OSConfigStatus_To_v1alpha1_OSConfigStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_node_OSConfig_To_v1alpha1_OSConfig is an autogenerated conversion function.
func Convert_node_OSConfig_To_v1alpha1_OSConfig(in *node.OSConfig, out *OSConfig, s conversion.Scope) error {
	return autoConvert_node_OSConfig_To_v1alpha1_OSConfig(in, out, s)
}

func autoConvert_v1alpha1_OSConfigList_To_node_OSConfigList(in *OSConfigList, out *node.OSConfigList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]node.OSConfig)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_OSConfigList_To_node_OSConfigList is an autogenerated conversion function.
func Convert_v1alpha1_OSConfigList_To_node_OSConfigList(in *OSConfigList, out *node.OSConfigList, s conversion.Scope) error {
	return autoConvert_v1alpha1_OSConfigList_To_node_OSConfigList(in, out, s)
}

func autoConvert_node_OSConfigList_To_v1alpha1_OSConfigList(in *node.OSConfigList, out *OSConfigList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]OSConfig)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_node_OSConfigList_To_v1alpha1_OSConfigList is an autogenerated conversion function.
func Convert_node_OSConfigList_To_v1alpha1_OSConfigList(in *node.OSConfigList, out *OSConfigList, s conversion.Scope) error {
	return autoConvert_node_OSConfigList_To_v1alpha1_OSConfigList(in, out, s)
}

func autoConvert_v1alpha1_OSConfigSpec_To_node_OSConfigSpec(in *OSConfigSpec, out *node.OSConfigSpec, s conversion.Scope) error {
	*out = *(*node.OSConfigSpec)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_OSConfigSpec_To_node_OSConfigSpec is an autogenerated conversion function.
func Convert_v1alpha1_OSConfigSpec_To_node_OSConfigSpec(in *OSConfigSpec, out *node.OSConfigSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_OSConfigSpec_To_node_OSConfigSpec(in, out, s)
}

func autoConvert_node_OSConfigSpec_To_v1alpha1_OSConfigSpec(in *node.OSConfigSpec, out *OSConfigSpec, s conversion.Scope) error {
	*out = *(*OSConfigSpec)(unsafe.Pointer(in))
	return nil
}

// Convert_node_OSConfigSpec_To_v1alpha1_OSConfigSpec is an autogenerated conversion function.
func Convert_node_OSConfigSpec_To_v1alpha1_OSConfigSpec(in *node.OSConfigSpec, out *OSConfigSpec, s conversion.Scope) error {
	return autoConvert_node_OSConfigSpec_To_v1alpha1_OSConfigSpec(in, out, s)
}

func autoConvert_v1alpha1_OSConfigStatus_To_node_OSConfigStatus(in *OSConfigStatus, out *node.OSConfigStatus, s conversion.Scope) error {
	*out = *(*node.OSConfigStatus)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_OSConfigStatus_To_node_OSConfigStatus is an autogenerated conversion function.
func Convert_v1alpha1_OSConfigStatus_To_node_OSConfigStatus(in *OSConfigStatus, out *node.OSConfigStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_OSConfigStatus_To_node_OSConfigStatus(in, out, s)
}

func autoConvert_node_OSConfigStatus_To_v1alpha1_OSConfigStatus(in *node.OSConfigStatus, out *OSConfigStatus, s conversion.Scope) error {
	*out = *(*OSConfigStatus)(unsafe.Pointer(in))
	return nil
}

// Convert_node_OSConfigStatus_To_v1alpha1_OSConfigStatus is an autogenerated conversion function.
func Convert_node_OSConfigStatus_To_v1alpha1_OSConfigStatus(in *node.OSConfigStatus, out *OSConfigStatus, s conversion.Scope) error {
	return autoConvert_node_OSConfigStatus_To_v1alpha1_OSConfigStatus(in, out, s)
}

func autoConvert_v1alpha1_StateBackup_To_node_StateBackup(in *StateBackup, out *node.StateBackup, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_StateBackupStatus_To_node_StateBackupStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_StateBackup_To_node_StateBackup is an autogenerated conversion function.
func Convert_v1alpha1_StateBackup_To_node_StateBackup(in *StateBackup, out *node.StateBackup, s conversion.Scope) error {
	return autoConvert_v1alpha1_StateBackup_To_node_StateBackup(in, out, s)
}

func autoConvert_node_StateBackup_To_v1alpha1_StateBackup(in *node.StateBackup, out *StateBackup, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_node_StateBackupStatus_To_v1alpha1_StateBackupStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_node_StateBackup_To_v1alpha1_StateBackup is an autogenerated conversion function.
func Convert_node_StateBackup_To_v1alpha1_StateBackup(in *node.StateBackup, out *StateBackup, s conversion.Scope) error {
	return autoConvert_node_StateBackup_To_v1alpha1_StateBackup(in, out, s)
}

func autoConvert_v1alpha1_StateBackupList_To_node_StateBackupList(in *StateBackupList, out *node.StateBackupList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]node.StateBackup)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_StateBackupList_To_node_StateBackupList is an autogenerated conversion function.
func Convert_v1alpha1_StateBackupList_To_node_StateBackupList(in *StateBackupList, out *node.StateBackupList, s conversion.Scope) error {
	return autoConvert_v1alpha1_StateBackupList_To_node_StateBackupList(in, out, s)
}

func autoConvert_node_StateBackupList_To_v1alpha1_StateBackupList(in *node.StateBackupList, out *StateBackupList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]StateBackup)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_node_StateBackupList_To_v1alpha1_StateBackupList is an autogenerated conversion function.
func Convert_node_StateBackupList_To_v1alpha1_StateBackupList(in *node.StateBackupList, out *StateBackupList, s conversion.Scope) error {
	return autoConvert_node_StateBackupList_To_v1alpha1_StateBackupList(in, out, s)
}

func autoConvert_v1alpha1_StateBackupStatus_To_node_StateBackupStatus(in *StateBackupStatus, out *node.StateBackupStatus, s conversion.Scope) error {
	*out = *(*node.StateBackupStatus)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_StateBackupStatus_To_node_StateBackupStatus is an autogenerated conversion function.
func Convert_v1alpha1_StateBackupStatus_To_node_StateBackupStatus(in *StateBackupStatus, out *node.StateBackupStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_StateBackupStatus_To_node_StateBackupStatus(in, out, s)
}

func autoConvert_node_StateBackupStatus_To_v1alpha1_StateBackupStatus(in *node.StateBackupStatus, out *StateBackupStatus, s conversion.Scope) error {
	*out = *(*StateBackupStatus)(unsafe.Pointer(in))
	return nil
}

// Convert_node_StateBackupStatus_To_v1alpha1_StateBackupStatus is an autogenerated conversion function.
func Convert_node_StateBackupStatus_To_v1alpha1_StateBackupStatus(in *node.StateBackupStatus, out *StateBackupStatus, s conversion.Scope) error {
	return autoConvert_node_StateBackupStatus_To_v1alpha1_StateBackupStatus(in, out, s)
}

func autoConvert_v1alpha1_Upgrade_To_node_Upgrade(in *Upgrade, out *node.Upgrade, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_UpgradeSpec_To_node_UpgradeSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_UpgradeStatus_To_node_UpgradeStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Upgrade_To_node_Upgrade is an autogenerated conversion function.
func Convert_v1alpha1_Upgrade_To_node_Upgrade(in *Upgrade, out *node.Upgrade, s conversion.Scope) error {
	return autoConvert_v1alpha1_Upgrade_To_node_Upgrade(in, out, s)
}

func autoConvert_node_Upgrade_To_v1alpha1_Upgrade(in *node.Upgrade, out *Upgrade, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_node_UpgradeSpec_To_v1alpha1_UpgradeSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_node_UpgradeStatus_To_v1alpha1_UpgradeStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_node_Upgrade_To_v1alpha1_Upgrade is an autogenerated conversion function.
func Convert_node_Upgrade_To_v1alpha1_Upgrade(in *node.Upgrade, out *Upgrade, s conversion.Scope) error {
	return autoConvert_node_Upgrade_To_v1alpha1_Upgrade(in, out, s)
}

func autoConvert_v1alpha1_UpgradeList_To_node_UpgradeList(in *UpgradeList, out *node.UpgradeList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]node.Upgrade)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_UpgradeList_To_node_UpgradeList is an autogenerated conversion function.
func Convert_v1alpha1_UpgradeList_To_node_UpgradeList(in *UpgradeList, out *node.UpgradeList, s conversion.Scope) error {
	return autoConvert_v1alpha1_UpgradeList_To_node_UpgradeList(in, out, s)
}

func autoConvert_node_UpgradeList_To_v1alpha1_UpgradeList(in *node.UpgradeList, out *UpgradeList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Upgrade)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_node_UpgradeList_To_v1alpha1_UpgradeList is an autogenerated conversion function.
func Convert_node_UpgradeList_To_v1alpha1_UpgradeList(in *node.UpgradeList, out *UpgradeList, s conversion.Scope) error {
	return autoConvert_node_UpgradeList_To_v1alpha1_UpgradeList(in, out, s)
}

func autoConvert_v1alpha1_UpgradeSpec_To_node_UpgradeSpec(in *UpgradeSpec, out *node.UpgradeSpec, s conversion.Scope) error {
	*out = *(*node.UpgradeSpec)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_UpgradeSpec_To_node_UpgradeSpec is an autogenerated conversion function.
func Convert_v1alpha1_UpgradeSpec_To_node_UpgradeSpec(in *UpgradeSpec, out *node.UpgradeSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_UpgradeSpec_To_node_UpgradeSpec(in, out, s)
}

func autoConvert_node_UpgradeSpec_To_v1alpha1_UpgradeSpec(in *node.UpgradeSpec, out *UpgradeSpec, s conversion.Scope) error {
	*out = *(*UpgradeSpec)(unsafe.Pointer(in))
	return nil
}

// Convert_node_UpgradeSpec_To_v1alpha1_UpgradeSpec is an autogenerated conversion function.
func Convert_node_UpgradeSpec_To_v1alpha1_UpgradeSpec(in *node.UpgradeSpec, out *UpgradeSpec, s conversion.Scope) error {
	return autoConvert_node_UpgradeSpec_To_v1alpha1_UpgradeSpec(in, out, s)
}

func autoConvert_v1alpha1_UpgradeStatus_To_node_UpgradeStatus(in *UpgradeStatus, out *node.UpgradeStatus, s conversion.Scope) error {
	*out = *(*node.UpgradeStatus)(unsafe.Pointer(in))
	return nil
}

// Convert_v1alpha1_UpgradeStatus_To_node_UpgradeStatus is an autogenerated conversion function.
func Convert_v1alpha1_UpgradeStatus_To_node_UpgradeStatus(in *UpgradeStatus, out *node.UpgradeStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_UpgradeStatus_To_node_UpgradeStatus(in, out, s)
}

func autoConvert_node_UpgradeStatus_To_v1alpha1_UpgradeStatus(in *node.UpgradeStatus, out *UpgradeStatus, s conversion.Scope) error {
	*out = *(*UpgradeStatus)(unsafe.Pointer(in))
	return nil
}

// Convert_node_UpgradeStatus_To_v1alpha1_UpgradeStatus is an autogenerated conversion function.
func Convert_node_UpgradeStatus_To_v1alpha1_UpgradeStatus(in *node.UpgradeStatus, out *UpgradeStatus, s conversion.Scope) error {
	return autoConvert_node_UpgradeStatus_To_v1alpha1_UpgradeStatus(in, out, s)
}
